### ISSUE TITLE
Use Nominatin to query for info and pass it to opening_hours.js to evaluate PH and sunrise stuff.

### ISSUE THREAD

**Issue by ypid** [dotevo/osm24#21]
As [some users](http://forum.openstreetmap.org/viewtopic.php?id=26748) are already wondering I open this issue which I already mentioned in #20.

See [opening_hours.js](https://github.com/ypid/opening_hours.js) for how to implement it.

**Comment by ypid** [comment]
Example: http://www.openstreetmap.org/node/2694888980
http://osm24.eu/index.php#!18/52.38826/9.74899/type=eat/mon=place_all/office=office_all/craft=craft_all/store=store_all/theatre_genre=theatre_genre_all/tourism_type=tourism_all/

**Comment by ypid** [comment]
Please check it out. You can peek at [my implementation](https://github.com/ypid/opening_hours.js/blob/1dadb87d899993b7e5f6fb30d5524c033d220c41/demo.html#L365).

**Comment by dotevo** [comment]
Is it possible to change nominatimJSON on demand?

**Comment by dotevo** [comment]
NVM :-)

**Comment by ypid** [comment]
Thanks very much :+1: It works with Chromium. But Firefox is complaining about the Same Origin Policy.
[Ways to circumvent the same-origin policy](http://stackoverflow.com/a/3076648).

**Comment by dotevo** [comment]
Do you have the same issue with overpass? I'm using $.ajax for overpass query also.

**Comment by ypid** [comment]
The problem seems to be my firefox settings. It works with a new profiles … Thanks for getting this done so quickly :) Now the German weekly task can go on :) http://blog.openstreetmap.de/blog/2015/04/wochenaufgabe-oeffnungszeiten/
