### ISSUE TITLE
Wrong status display of a node

### ISSUE THREAD

**Issue by hjoertel** [dotevo/osm24#35]
node/265799694 "Saigon Place" is displayed as having no data for opening_hours, But it has well formed data. http://ypid.de/~osm/ shows it correct. 
Mo-Sa 11:30-15:00, 17:00-23:00; Su 11:30-23:00; PH 11:30-23:00

Let me know if you need my help.

**Comment by dotevo** [comment]
Hi. PH is still missing on osm24. It will be added in osm24 v2. Thank you.

**Comment by ypid** [comment]
Related to #21.

**Comment by dotevo** [comment]
Fixed
