### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by hermann-san** [dotevo/osm24#38]
I'd like to translate  the website into german language, but I'm not a developer.
I've seen that somebody has translated into Ukraine language and that all data is in the uk_UA.php file is.
How can I get the latest file and would you accept a translation from me?
regards,
Hermann

**Comment by dotevo** [comment]
Hi,

The last file is here:
https://github.com/dotevo/osm24/blob/master/lang/en_EN.php
Of course I will be nice if you translate file :-)

Translation example is here:
https://github.com/dotevo/osm24/blob/master/lang/it_IT.php

Br,
Adam

**Comment by hermann-san** [comment]
define('PANEL_EMPTY','Vuoto');
define('PANEL_NO','No');
define('PANEL_YES','Sì');
define('PANEL_DEDICATED','Dedicato');
define('PANEL_ISOLATED','Isolato');
define('PANEL_SEPARATED','Separato');

**Comment by hermann-san** [comment]
![german](https://cloud.githubusercontent.com/assets/7679654/5959131/cce08d34-a7cb-11e4-911d-bf0e8e6dcab8.png)

**Comment by dotevo** [comment]
Thank you.
