### ISSUE TITLE
Language selection doesn't work

### ISSUE THREAD

**Issue by hermann-san** [dotevo/osm24#39]
it seems like there is only english language available.
I've checked again my german translation for syntax errors, but all seems ok to me.  
Not sure if german special characters can become a problem.

**Comment by dotevo** [comment]
Is this link working for you? http://osm24.eu/?lang=de_DE

**Comment by hermann-san** [comment]
it come's up in english language

**Comment by edewaele** [comment]
Hi,

This is certainly an issue with the system that runs osm24.eu. I installed the application on my own VPS, and it works fine http://dewaele.ovh/osm24/?lang=de_DE

**Comment by dotevo** [comment]
On my server also works fine http://osm24.eu/?lang=de_DE :-/ I don't know where is the issue.

**Comment by edewaele** [comment]
![tmp_26657-screenshot_2015-04-30-10-00-13-1580201224](https://cloud.githubusercontent.com/assets/1607217/7408707/ea769d70-ef1f-11e4-865f-edc8ca53ef66.jpeg)

This is what I get on my phone. The result is similar an a desktop.

**Comment by hermann-san** [comment]
I also tried it on a different PC with Firefox, IE and Chrome. The result is always the same. Only english language available


![osm](https://cloud.githubusercontent.com/assets/7679654/7411151/6f9d30a8-ef35-11e4-99eb-6eb8f3e55fa9.png)

**Comment by edewaele** [comment]
I suppose that this issue is linked with #32. The configuration of osm24.eu should be checked. Is this copy synchronised with the git repository ?

**Comment by dotevo** [comment]
Can someone check Nicolas's patch? New version is available on http://osm24.eu/fortests/index.php

**Comment by hermann-san** [comment]
the languages work.
the flag description is still missing.

**Comment by dotevo** [comment]
What do you mean "description"? Are you talking about language name? Something like 
"[IMG] English"
"[IMG] Deutsch"

**Comment by hermann-san** [comment]
yes, AFAIK in the past it was there.
