### ISSUE TITLE
osm24.eu gone?

### ISSUE THREAD

**Issue by afita** [dotevo/osm24#46]
When I access www.osm24.eu I am presented with a page with "CT8.PL • Darmowy hosting WWW ".

Did the domain name expire?

Will you bring back the site?

**Comment by baditaflorin** [comment]
Can confirm here. Can we help in any way ?

**Comment by dotevo** [comment]
The website will be moved to a new hosting today.

**Comment by afita** [comment]
osm24.eu is back. Thanks.

Closing.

**Comment by dotevo** [comment]
No problem. It was my fault :-/
