### ISSUE TITLE
Large Overpass queries

### ISSUE THREAD

**Issue by mmd-osm** [dotevo/osm24#49]
Currently each node in a query comes with its own bbox (see https://github.com/dotevo/osm24/blob/master/js/query.js#L142). A better approach could be to use a global bbox instead and only provide the bbox once for the whole query.

Example:

``` C
[out:json][bbox:51.83492893182609,17.100219726562496,52.22906116068751,18.384933471679688];
(node['amenity'='restaurant'];
 node['amenity'='fast_food'];
 node['amenity'='cafe'];
 node['amenity'='ice_cream'];
  node['amenity'='bank'];);out 40;
```

**Comment by dotevo** [comment]
Sounds good. I've never seen this global variable before. Thx.
