### ISSUE TITLE
Some ideas for performance improvements

### ISSUE THREAD

**Issue by mmd-osm** [dotevo/osm24#57]
I just wanted post this issue as a follow for [this Forum post](https://forum.openstreetmap.org/viewtopic.php?pid=616392#p616392).

_After a bit of analysis it turned out that the queries created by osm24 are not really ideal, as in the following example: http://overpass-turbo.eu/s/jPw (about 15s runtime). The optimized version using regular expressions just takes 2.7s (http://overpass-turbo.eu/s/jPx)._

**Comment by dotevo** [comment]
I've started a new version of OSM24 also with cache and storage but I do not have enough time to finish. But thank you for your comment. I think that osm24 need many improvements.
